### PR TITLE
Set up project structure

### PR DESCRIPTION
**Pull request by zsommers**
Created project called rylviach_site and app called landing_page
Created detailed settings and requirements
Changed README from .md to .rst but didn't edit content

### CODE REVIEW

**Comment by zsommers** [comment]
@rlbaker @SMLuthi Take a look and see if this makes sense

**Comment by zsommers** [comment]
Forgot to associate with [ch21]

**Comment by rlbaker** [comment]
- [x] Sexy
- [x] Looks Good To Me

**Comment by rlbaker** [comment]
- [x]

**Comment by SMLuthi** [comment]
- [x] This a checkbox

**Comment by rlbaker** [comment]
- [ ] @zsommers 
- [ ] @SMLuthi

**Comment by rlbaker** [comment]
LGTM

**Comment by SMLuthi** [comment]
(corpsethumb)

**Pull request merged**
